guzzle:
    clients:
        api_geo_list:
            base_url: "https://restcountries.eu"
            headers:
                Accept: "application/json"
        api_language_list:
            base_url: "http://ws.detectlanguage.com"
            headers:
                Accept: "application/json"
        api_currency_list:
            base_url: "https://openexchangerates.org"
            headers:
                Accept: "application/json"
miky_resource:
    resources:
        miky.location:
            classes:
                model: %miky_location.model.location.class%